// Need to use the React-specific entry point to import `createApi`
import { createApi } from "@reduxjs/toolkit/query/react";

import { getBaseQuery } from "@/lib/common";

// Define a service using a base URL and expected endpoints
export const monthListApiSlice = createApi({
  baseQuery: getBaseQuery("dates"),
  reducerPath: "monthApi",
  // Tag types are used for caching and invalidation.
  tagTypes: ["Month"],
  endpoints: (build) => ({
    // Supply generics for the return type (in this case `QuotesApiResponse`)
    // and the expected query argument. If there is no argument, use `void`
    // for the argument type instead.
    getMonthList: build.query<
      { dates?: string[]; error?: string },
      { url: string; date: string }
    >({
      query: (queryData) =>
        `?date=${queryData.date}&url=${encodeURIComponent(queryData.url)}`,
      // `providesTags` determines which 'tag' is attached to the
      // cached data returned by the query.
      providesTags: (result, error, queryData) => [
        { type: "Month", id: queryData.url + queryData.date },
      ],
    }),
  }),
});

// Hooks are auto-generated by RTK-Query
// Same as `quotesApiSlice.endpoints.getQuotes.useQuery`
export const { useGetMonthListQuery } = monthListApiSlice;
